### ISSUE TITLE
WARNING: Base.FloatingPoint is deprecated, use AbstractFloat instead.

### ISSUE THREAD

**Issue by knuds** [Andy-P/RecurrentNN.jl#9]
When installing with Pkg.clone("https://github.com/Andy-P/RecurrentNN.jl.git")  I get:
WARNING: Base.FloatingPoint is deprecated, use AbstractFloat instead.
  likely near ~/.julia/RecurrentNN/src/recurrent.jl:13

**Comment by Andy-P** [comment]
This library is longer supported. I suggest you use [MxNet.jl](http://dmlc.ml/MXNet.jl/). There is a [good example of an LSTM here](http://dmlc.ml/MXNet.jl/latest/tutorial/char-lstm/)
